[project]
src = "src"
out = "out"
dot_env = ".env"
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = true
chain_id = 31337
default_account_name = "anvil0"
unsafe_password_file = "$ANVIL_PASSWORD_PATH"

[networks.anvil.contracts.mood_nft]
deployer_script = "script/deploy_mood_nft.py"

[networks.anvil-zksync]
is_zksync = true
url = "http://127.0.0.1:8011"
prompt_live = false
save_to_db = false
chain_id = 260
default_account_name = "anvil0-zksync"
unsafe_password_file = "$ANVIL_ZKSYNC_PASSWORD_PATH"


[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
